### ISSUE TITLE
Errors when running container

### ISSUE THREAD

**Issue by benderstwin** [finish06/Unifi-Metrics-Collector#1]
Hi there, thank you for putting this together.  I'm trying to get this set up but when I run the container I get some errors.  Maybe someone can point me in the right direction?  I have tried it with SSL yes and no.  Same errors.

```
 /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./unifi_collector.py", line 116, in run
    ssl_verify=ssl))
  File "./unifi_collector.py", line 25, in __init__
    self._update()
  File "./unifi_collector.py", line 32, in _update
    self._stack_info = {item['name']: item for item in stack}
  File "./unifi_collector.py", line 32, in <dictcomp>
    self._stack_info = {item['name']: item for item in stack}
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./unifi_collector.py", line 191, in <module>
    run()
  File "./unifi_collector.py", line 118, in run
    logger.error('Unifi Controller error: ' % err)
TypeError: not all arguments converted during string formatting
```

**Comment by finish06** [comment]
Did you try `ssl = False`?

**Comment by finish06** [comment]
What are the names of your UBNT equipment?  Do you use special characters?

**Comment by benderstwin** [comment]
I have tried ssl = false

Some of the names do have special characters.  I'll try to get rid of them and see if that changes anything.

**Comment by benderstwin** [comment]
> What are the names of your UBNT equipment? Do you use special characters?

After renaming, it seems to work.  Only one error I see says 
```
USG3 rx/tx error: list index out of range
```

**Comment by finish06** [comment]
Hmmm....  I will have to dig into figure that out.

**Comment by benderstwin** [comment]
Let me know if I can provide any useful information!

**Comment by finish06** [comment]
You were on to it.  The item had to have a name assigned to it in the Unifi controller.  That is still a dependency of this code.
