### ISSUE TITLE
Unable to write to InfluxDB

### ISSUE THREAD

**Issue by mehrenreich** [finish06/Unifi-Metrics-Collector#3]
When starting the Docker container (either stand-alone or with docker-compose), I get the following error message:

```
unifi-metrics-collector_1  | Traceback (most recent call last):
unifi-metrics-collector_1  |   File "./unifi_collector.py", line 191, in <module>
unifi-metrics-collector_1  |     run()
unifi-metrics-collector_1  |   File "./unifi_collector.py", line 170, in run
unifi-metrics-collector_1  |     stats[0])
unifi-metrics-collector_1  | KeyError: 0
```

A database exists as well as the credentials, also the port is open and the database reachable from my machine. Setting logging to DEBUG also shows me that querying the Unifi AP is working and I'm getting results.

Is there a way to make this part of the Python script more verbose?

**Comment by finish06** [comment]
I have started working on this script again. Unifi had made changes to the API since the last time.  Currently, it only handles switches, but I intend to improve on that.  Sorry for the delayed response.  I am going to close this as it now works again.
